-- Schema metadata inspected read-only on 2026-10-05. Synthetic rows only.
CREATE ROLE anon NOLOGIN NOBYPASSRLS;
CREATE ROLE authenticated NOLOGIN NOBYPASSRLS;
CREATE ROLE service_role NOLOGIN BYPASSRLS;
CREATE SCHEMA auth;
CREATE SCHEMA supabase_migrations;
CREATE TABLE supabase_migrations.schema_migrations(version text PRIMARY KEY);
CREATE TABLE auth.users(id uuid PRIMARY KEY);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
$$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT USAGE ON SCHEMA public, auth TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION auth.uid() TO anon, authenticated, service_role;
CREATE TABLE public.businesses (
  allow_cancellation boolean DEFAULT false NOT NULL,
  cancellation_deadline_minutes integer DEFAULT 0 NOT NULL,
  cancellation_fee_enabled boolean DEFAULT false NOT NULL,
  instagram_enabled boolean DEFAULT false,
  messenger_enabled boolean DEFAULT false,
  timezone text DEFAULT 'Europe/Stockholm'::text,
  language text DEFAULT 'sv'::text,
  whatsapp_enabled boolean DEFAULT false,
  admin_notification_channel text DEFAULT 'telegram'::text,
  cancellation_fee_amount numeric(12,2) DEFAULT 0 NOT NULL,
  cancellation_fee_currency text DEFAULT 'SEK'::text NOT NULL,
  services jsonb DEFAULT '[]'::jsonb NOT NULL,
  ai_tone_config jsonb DEFAULT jsonb_build_object('tonePreset', 'professional', 'responseLength', 'balanced', 'emojiUsage', 'none', 'formality', 'balanced', 'customToneInstructions', '') NOT NULL,
  industry text,
  whatsapp_access_token text,
  admin_telegram_chat_id text,
  whatsapp_phone_number_id text,
  business_name text NOT NULL,
  messenger_page_id text,
  whatsapp_business_account_id text,
  whatsapp_verify_token text,
  custom_system_prompt text,
  admin_whatsapp_number text,
  instagram_access_token text,
  working_hours jsonb,
  instagram_page_id text,
  messenger_page_access_token text,
  google_calendar_id text,
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  telegram_bot_token text,
  instagram_verify_token text,
  instagram_account_id text
);
CREATE TABLE public.business_memberships (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  business_id bigint NOT NULL,
  created_by uuid,
  user_id uuid NOT NULL,
  role text NOT NULL
);
CREATE TABLE public.salons (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  status text,
  business_id text NOT NULL,
  salon_name text NOT NULL
);
ALTER TABLE public.businesses ADD CONSTRAINT businesses_pkey PRIMARY KEY (id);
ALTER TABLE public.salons ADD CONSTRAINT salons_business_id_key UNIQUE (business_id);
ALTER TABLE public.salons ADD CONSTRAINT salons_pkey PRIMARY KEY (id);
ALTER TABLE public.businesses ADD CONSTRAINT businesses_cancellation_deadline_nonnegative CHECK ((cancellation_deadline_minutes >= 0));
ALTER TABLE public.businesses ADD CONSTRAINT businesses_cancellation_fee_nonnegative CHECK ((cancellation_fee_amount >= (0)::numeric));
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_business_id_positive CHECK ((business_id > 0));
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_role_valid CHECK (((role = btrim(role)) AND (role = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text, 'agent'::text, 'viewer'::text]))));
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_status_valid CHECK (((status = btrim(status)) AND (status = ANY (ARRAY['active'::text, 'invited'::text, 'suspended'::text, 'revoked'::text]))));
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_timestamps_valid CHECK ((updated_at >= created_at));
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_pkey PRIMARY KEY (id);
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_business_user_key UNIQUE (business_id, user_id);
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.business_memberships ADD CONSTRAINT business_memberships_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.businesses ADD CONSTRAINT businesses_ai_tone_config_shape CHECK (((jsonb_typeof(ai_tone_config) = 'object'::text) AND (ai_tone_config ?& ARRAY['tonePreset'::text, 'responseLength'::text, 'emojiUsage'::text, 'formality'::text, 'customToneInstructions'::text]) AND (jsonb_typeof((ai_tone_config -> 'tonePreset'::text)) = 'string'::text) AND ((ai_tone_config ->> 'tonePreset'::text) = ANY (ARRAY['professional'::text, 'friendly'::text, 'warm'::text, 'casual'::text, 'concise'::text, 'custom'::text])) AND (jsonb_typeof((ai_tone_config -> 'responseLength'::text)) = 'string'::text) AND ((ai_tone_config ->> 'responseLength'::text) = ANY (ARRAY['short'::text, 'balanced'::text, 'detailed'::text])) AND (jsonb_typeof((ai_tone_config -> 'emojiUsage'::text)) = 'string'::text) AND ((ai_tone_config ->> 'emojiUsage'::text) = ANY (ARRAY['none'::text, 'light'::text, 'expressive'::text])) AND (jsonb_typeof((ai_tone_config -> 'formality'::text)) = 'string'::text) AND ((ai_tone_config ->> 'formality'::text) = ANY (ARRAY['formal'::text, 'balanced'::text, 'casual'::text])) AND (jsonb_typeof((ai_tone_config -> 'customToneInstructions'::text)) = 'string'::text) AND (length((ai_tone_config ->> 'customToneInstructions'::text)) <= 500)));

-- Incoming FK tables use minimal columns: only deletion semantics are modeled.
CREATE TABLE public.calendar_authorization_sessions(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT calendar_authorization_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.appointments(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT appointments_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id));
CREATE TABLE public.business_notifications(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT business_notifications_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.knowledge_sources(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT knowledge_sources_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.booking_slot_reservations(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT booking_slot_reservations_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.booking_result_outbox(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT booking_result_outbox_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.channel_connections(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT channel_connections_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.channel_authorization_sessions(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT channel_authorization_sessions_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.calendar_connections(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT calendar_connections_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE TABLE public.knowledge_chunks(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id bigint, CONSTRAINT knowledge_chunks_business_id_fkey FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE);
CREATE OR REPLACE FUNCTION public.set_business_membership_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog'
AS $function$
begin
  new.updated_at = greatest(now(), new.created_at);
  return new;
end;
$function$
;
REVOKE ALL ON FUNCTION public.set_business_membership_updated_at() FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.set_business_membership_updated_at() TO service_role;
CREATE OR REPLACE FUNCTION public.delete_business_with_memberships(p_business_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog'
AS $function$
declare
  deleted_business_count integer;
begin
  if p_business_id is null or p_business_id <= 0 then
    raise exception using errcode = '22023', message = 'invalid_business_id';
  end if;

  perform 1
  from public.businesses
  where id = p_business_id
  for update;

  if not found then
    return false;
  end if;

  delete from public.business_memberships
  where business_id = p_business_id;

  delete from public.businesses
  where id = p_business_id;

  get diagnostics deleted_business_count = row_count;
  if deleted_business_count <> 1 then
    raise exception using errcode = 'P0001', message = 'business_delete_failed';
  end if;

  return true;
end;
$function$
;
REVOKE ALL ON FUNCTION public.delete_business_with_memberships(p_business_id bigint) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.delete_business_with_memberships(p_business_id bigint) TO service_role;
CREATE OR REPLACE FUNCTION public.create_business_with_owner(p_owner_user_id uuid, p_business_name text, p_telegram_bot_token text, p_google_calendar_id text, p_custom_system_prompt text, p_instagram_page_id text, p_instagram_account_id text, p_instagram_access_token text, p_instagram_verify_token text, p_instagram_enabled boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'pg_catalog'
AS $function$
declare
  created_business public.businesses%rowtype;
begin
  if p_owner_user_id is null then
    raise exception using errcode = '22004', message = 'owner_user_id_required';
  end if;

  if nullif(btrim(p_business_name), '') is null then
    raise exception using errcode = '22023', message = 'business_name_required';
  end if;

  insert into public.businesses (
    business_name,
    telegram_bot_token,
    google_calendar_id,
    custom_system_prompt,
    instagram_page_id,
    instagram_account_id,
    instagram_access_token,
    instagram_verify_token,
    instagram_enabled
  )
  values (
    btrim(p_business_name),
    coalesce(p_telegram_bot_token, ''),
    coalesce(p_google_calendar_id, ''),
    coalesce(p_custom_system_prompt, ''),
    coalesce(p_instagram_page_id, ''),
    coalesce(p_instagram_account_id, ''),
    coalesce(p_instagram_access_token, ''),
    coalesce(p_instagram_verify_token, ''),
    coalesce(p_instagram_enabled, false)
  )
  returning * into created_business;

  insert into public.business_memberships (
    business_id,
    user_id,
    role,
    status,
    created_by
  )
  values (
    created_business.id,
    p_owner_user_id,
    'owner',
    'active',
    p_owner_user_id
  );

  return jsonb_build_object(
    'id', created_business.id,
    'business_name', created_business.business_name,
    'industry', created_business.industry,
    'timezone', created_business.timezone,
    'language', created_business.language,
    'custom_system_prompt', created_business.custom_system_prompt,
    'google_calendar_id', created_business.google_calendar_id,
    'instagram_page_id', created_business.instagram_page_id,
    'instagram_account_id', created_business.instagram_account_id,
    'messenger_page_id', created_business.messenger_page_id,
    'whatsapp_phone_number_id', created_business.whatsapp_phone_number_id,
    'whatsapp_business_account_id', created_business.whatsapp_business_account_id
  );
end;
$function$
;
REVOKE ALL ON FUNCTION public.create_business_with_owner(p_owner_user_id uuid, p_business_name text, p_telegram_bot_token text, p_google_calendar_id text, p_custom_system_prompt text, p_instagram_page_id text, p_instagram_account_id text, p_instagram_access_token text, p_instagram_verify_token text, p_instagram_enabled boolean) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.create_business_with_owner(p_owner_user_id uuid, p_business_name text, p_telegram_bot_token text, p_google_calendar_id text, p_custom_system_prompt text, p_instagram_page_id text, p_instagram_account_id text, p_instagram_access_token text, p_instagram_verify_token text, p_instagram_enabled boolean) TO service_role;
CREATE TRIGGER business_memberships_set_updated_at BEFORE UPDATE ON public.business_memberships FOR EACH ROW EXECUTE FUNCTION set_business_membership_updated_at();

COMMENT ON COLUMN business_memberships.business_id IS 'Business bigint identifier. Deliberately not foreign-keyed so membership cannot block operational business deletion.';
GRANT ALL ON TABLE businesses, salons TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE businesses_id_seq TO anon, authenticated, service_role;
GRANT SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON business_memberships TO anon, authenticated;
GRANT ALL ON business_memberships TO service_role;
ALTER TABLE business_memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY business_memberships_read_own_active ON business_memberships FOR SELECT TO authenticated USING(auth.uid()=user_id AND status='active');
CREATE INDEX business_memberships_user_status_business_idx ON business_memberships(user_id,status,business_id);
CREATE INDEX business_memberships_business_status_user_idx ON business_memberships(business_id,status,user_id);
INSERT INTO auth.users VALUES ('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');
INSERT INTO businesses(id,business_name,telegram_bot_token,whatsapp_access_token) VALUES(2,'Synthetic A','private-a','private-wa-a'),(3,'Synthetic B','private-b','private-wa-b');
SELECT setval('businesses_id_seq',3);
INSERT INTO business_memberships(business_id,user_id,role) VALUES(2,'11111111-1111-4111-8111-111111111111','owner'),(3,'22222222-2222-4222-8222-222222222222','owner');
INSERT INTO salons(salon_name,business_id) VALUES('chichi','chi');
